apiVersion: v1
kind: Namespace
metadata:
  name: server
---
apiVersion: v1
kind: Pod
metadata:
  name: fileserver
  namespace: server
  labels:
    app: fileserver
spec:
  containers:
    - name: serve-files
      image: harshitadocker/serve-files:v1
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: server
spec:
  selector:
    app: fileserver
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: indeserver
  namespace: server
  labels:
    app: indeserver
spec:
    containers:
      - name: serve-files
        image: harshitadocker/serve-files:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080   
---
apiVersion: v1
kind: Service
metadata:
  name: index-service
  namespace: server
spec:
  selector:
    app: indeserver
  ports:
    - port: 80
      targetPort: 8080
    
    